blank_issues_enabled: false
contact_links:
  - name: Create an issue or Report a bug
    url: https://github.com/ameax/datev-xml/issues/new
    about: Create an issue or Report a reproducable bug
  - name: Ask a question
    url: https://github.com/ameax/datev-xml/discussions/new?category=q-a
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/ameax/datev-xml/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/ameax/datev-xml/security/policy
    about: Learn how to notify us for sensitive bugs
